[WIP] Fix MisteryMania - Updated
hikari-no-yume/touchHLE pull request #111
Opened 2023-05-09 16:05 UTC by KiritoDv

This PR tries to fix an old game called mistery mania, It implements this functions and classes:

 * [Implemented fgetc](https://github.com/hikari-no-yume/touchHLE/commit/6e1ac76b432a46d4da5aaf7bf69f3a5699f66119)
 * [Implemented CGData](https://github.com/hikari-no-yume/touchHLE/commit/734560cf926c34946fe01b15682cddb3eb8a9759)
 * [Implemented NSClass](https://github.com/hikari-no-yume/touchHLE/commit/74d4e449894c668a9b320b537fffe50c3c15bfe4)
 * [Implemented NSBundle::infoDictionary](https://github.com/hikari-no-yume/touchHLE/commit/d12d7e2673841d5a2ecf83f9e317aef2a57383e1)
 * [Implemented CGImageCreateWithPNGDataProvider](https://github.com/hikari-no-yume/touchHLE/commit/1e5d120f7428b482b35750632f9f14b51285a522)
 * [Implemented TexParameteriv, TexSubImage2D, BufferData & Color4ub](https://github.com/hikari-no-yume/touchHLE/commit/b59540bd088ea9ab3c46747ea74d59bd6a35f8ce)

2023-05-26 16:14 UTC, GamingDuckingalt commented
i don't understand why this PR is closed

2023-07-17 16:48 UTC, hikari-no-yume commented on src/frameworks/opengles/gles_generic.rs
> +    unsafe fn BufferData(
Can you move this to the buffers section? (same in the other files)

2023-07-17 16:58 UTC, hikari-no-yume commented
I cherry-picked the `fgetc` commit to trunk now (79389dfd0a00df08ceb4f60646ac47aebc488b07).

2023-07-17 17:03 UTC, hikari-no-yume requested changes
Sorry I took so long to look at this… I have some suggestions.

Note to self: I need to look closer at the CGDataProvider thing at some point.

2023-07-17 17:03 UTC, hikari-no-yume commented on src/frameworks/opengles/gles1_native.rs
> +    }
Can you move this to the buffers section? (same in the other files)

2023-07-17 17:03 UTC, hikari-no-yume commented on src/frameworks/opengles/gles1_native.rs
> +    }
Can you move this to where the other `Color` functions are? (same in the other files)

2023-07-17 17:03 UTC, hikari-no-yume commented on src/libc/stdio/printf.rs
> +            b'x' => {
Can you put the `%x` part in a separate commit from the `vsnprintf` change?

2023-07-17 17:03 UTC, hikari-no-yume commented on src/image.rs
> +            pixels.as_mut_ptr()
Please also change `CGImageGetAlphaInfo` so it returns the appropriate constant now (and update the comments in it — you can remove the `TODO`).

2023-07-17 17:03 UTC, hikari-no-yume commented on src/frameworks/foundation/ns_class.rs
> +    msg![env; nil new]
Can you change it to use `get_known_class`, but first have it check if the class is `MPMediaPickerControllerDelegate` and if so return nil? (You can precede it with a comment explaining it's a hack for Mystery Mania and why.)

2023-07-17 17:03 UTC, hikari-no-yume commented on src/frameworks/foundation/ns_bundle.rs
> +}
If we're going to have this hack, can you add a log message, something like `log!("TODO: [(NSBundle*){:?} infoDictionary] (returning nil)", this);`, so if an app uses this and breaks, there'll be a clue for the problem in the log?

2023-07-25 15:02 UTC, hikari-no-yume commented
I needed the premultiplied alpha thing for something else, and in the process I discovered a bug with your version. Since I wanted other changes made to it anyway, I realised I might as well write my own: 48266f3904987cb4ac30f2085b133f93608cd437. You can drop your commit I guess. Sorry for the wasted effort.

2023-08-26 17:39 UTC, hikari-no-yume commented
I ended up having to reimplement a lot of stuff from this pull request in order to save time. Also, I did some work to debug the mysterious audio crashes that required the GDB hacks, and fixed the root cause in e8aceef416e5ed9e19d99adc83793300f6bfdf33. And now (as of d096a8bd305f1503e197f82857ce242c6d2b1617) I'm happy to report that Mystery Mania 1.1.0 is working on trunk!

![screenshot of the title screen](https://github.com/hikari-no-yume/touchHLE/assets/579774/d6a57db5-3d22-4345-9893-a7584fb3dfe8)
![in-game screenshot](https://github.com/hikari-no-yume/touchHLE/assets/579774/ba177034-89c9-40cd-8c57-4ef0c166b3d4)

With that, I can close the PR.

2023-08-26 17:39 UTC, closed without merging