Resident Evil 4 Mobile Edition
hikari-no-yume/touchHLE pull request #233
Opened 2024-01-12 19:10 UTC by alborrajo

# Tested versions

- 1.00.00

# Known issues

- Doesn't play video cutscenes
- No sound effects

# Screenshots

<img width="1072" alt="imagen" src="https://github.com/hikari-no-yume/touchHLE/assets/38296782/3cc95afb-66bf-4b82-bb2f-6ea2019e11ba">
<img width="1072" alt="imagen" src="https://github.com/hikari-no-yume/touchHLE/assets/38296782/cdd6f498-7ac2-435e-b868-25b2664e6e88">

2024-01-12 23:51 UTC, omagadsamsa commented
When I press the settings button the game crashes

2024-01-13 00:24 UTC, omagadsamsa commented
in this build there are no sound effects in many games

2024-01-21 20:55 UTC, omagadsamsa commented
![image](https://github.com/hikari-no-yume/touchHLE/assets/149837198/4cabe880-545a-4cf6-91b1-d6a2e629f357)
There is still sound stuttering in your build

2024-01-26 16:41 UTC, omagadsamsa commented
in the previous build the sound effects returned

2024-02-02 10:24 UTC, omagadsamsa commented
omg
![image](https://github.com/hikari-no-yume/touchHLE/assets/149837198/62b996fc-c399-441b-b769-10c307bffbe2)

2024-02-25 05:24 UTC, bmwm111 commented
hi please help mi how to download games touchhle emulator instaled my phone , game download please

2024-02-25 05:26 UTC, bmwm111 commented
![Screenshot_20240225_092511](https://github.com/hikari-no-yume/touchHLE/assets/161166787/6dff3b4f-a7a1-46ba-b578-eeeaf4526552)

2024-03-04 22:18 UTC, omagadsamsa commented
build for android no work re4

2024-03-05 09:17 UTC, hikari-no-yume commented on src/frameworks/av_audio/av_audio_player.rs
> +    // TODO: Check for errors, return nil and write them to error if there are
test of per-commit github reviews

2024-03-05 09:17 UTC, hikari-no-yume requested changes
test

2024-03-05 09:17 UTC, hikari-no-yume commented on src/frameworks/av_audio/av_audio_player.rs
> +    // TODO: Check for errors, return nil and write them to error if there are
*puts on testing hat* i think you should change this

2024-03-05 09:19 UTC, hikari-no-yume commented on src/frameworks/av_audio/av_audio_player.rs
> +    // TODO: Check for errors, return nil and write them to error if there are
Cool, so I can actually leave reviews on just a single commit in a pull and the comment _will_ show up on the pull request and _won't_ forget the context?

2024-03-21 08:14 UTC, thundergun1 commented
I've noticed a couple of issues on Android. Firstly, whenever a use prompt appears (Open Door, Raise Ladder etc) a big chunk of geometry disappears, though reappears when the prompt leaves.

Also, the accelerometer doesn't seem to work, as even on the highest shake sensitivity I can't reload by shaking my phone.

Apologies for possibly nagging on both of your PRs, it's fantastic work overall I just thought I'd point out some issues I've had

![Screenshot_20240321_081024_touchHLE](https://github.com/touchHLE/touchHLE/assets/133943803/3553a286-5b26-4898-971c-3913b35e7b57)
![Screenshot_20240321_080810_touchHLE](https://github.com/touchHLE/touchHLE/assets/133943803/f169f151-debf-468d-b37a-3a11188d9d7a)

2024-03-22 15:49 UTC, alborrajo commented
I've been playing on Android and I haven't seen this issue before. Considering you also had the other issue with the RE Degeneration splash screen which i couldn't replicate, couldn't be an issue on your Android version? Please provide more details about the device you're using.

About reloading, i have my suspicion that is related to the issue #151 as I can't reload on my phone either.

2024-03-22 16:08 UTC, thundergun1 commented
Of course. I'm using a Samsung Galaxy A42 with an Adreno GPU running Android 12.

I'm unsure regarding the accelerometer. I currently have 3 different apks of TouchHLE saved (one for your RE4 PR, one for your Degeneration PR, and one for the trunk) and on the latter 2 the accelerometer works perfectly on any game that uses it, whereas on the apk for the RE4 PR it doesn't, even for games like CNK3D where it works great on the other builds

2024-03-23 17:52 UTC, SonicVrey requested changes
Ok

2024-04-07 11:03 UTC, thundergun1 commented
Leon seems to have stopped existing as of this newest build, though his gun is still present.

![Screenshot_20240407_115657_touchHLE](https://github.com/touchHLE/touchHLE/assets/133943803/8b51ff90-adea-4295-856e-b21554e3e600)

Also it may be that the disappearing graphics I mentioned earlier could be an issue with Adreno GPUs rather than an issue with your PR

2024-04-07 15:07 UTC, alborrajo commented
> Leon seems to have stopped existing as of this newest build, though his gun is still present.

Try again with the latest build

2024-04-07 15:22 UTC, thundergun1 commented
Can confirm Leon is back

2024-06-22 19:56 UTC, DrPonx commented
could u comebine both resident evil 4 and Degeneration into one workflow

2024-06-22 22:27 UTC, thundergun1 commented
Although the accelerometer bug as of a few commits ago, it still doesn't seem to work on the latest build of your PR

2024-07-06 17:20 UTC, celerizer commented
Here is a slightly playable controller mapping for anyone interested (use UI layout 1):
```
jp.co.capcom.res4: --landscape-left --button-to-touch=DPadUp,72,198 --button-to-touch=DPadDown,72,292 --button-to-touch=DPadLeft,24,246 --button-to-touch=DPadRight,120,246 --button-to-touch=X,440,210 --button-to-touch=LeftShoulder,405,280 --button-to-touch=A,370,210 --button-to-touch=B,440,140 --button-to-touch=Y,370,140
```

2024-09-14 09:44 UTC, merged

2024-09-14 09:46 UTC, alborrajo commented
This branch is now merged with trunk 🎉